# This is a basic workflow to help you get started with Actions

name: Sample Build File

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
      runs-on: ubuntu-latest
      steps:
      - name: Run a one-line script
        run: echo Hello, Delete Test!
